// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// ArtifactRepositoryRefApplyConfiguration represents an declarative configuration of the ArtifactRepositoryRef type for use
// with apply.
type ArtifactRepositoryRefApplyConfiguration struct {
	ConfigMap *string `json:"configMap,omitempty"`
	Key       *string `json:"key,omitempty"`
}

// ArtifactRepositoryRefApplyConfiguration constructs an declarative configuration of the ArtifactRepositoryRef type for use with
// apply.
func ArtifactRepositoryRef() *ArtifactRepositoryRefApplyConfiguration {
	return &ArtifactRepositoryRefApplyConfiguration{}
}

// WithConfigMap sets the ConfigMap field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ConfigMap field is set to the value of the last call.
func (b *ArtifactRepositoryRefApplyConfiguration) WithConfigMap(value string) *ArtifactRepositoryRefApplyConfiguration {
	b.ConfigMap = &value
	return b
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *ArtifactRepositoryRefApplyConfiguration) WithKey(value string) *ArtifactRepositoryRefApplyConfiguration {
	b.Key = &value
	return b
}
