// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// CounterApplyConfiguration represents an declarative configuration of the Counter type for use
// with apply.
type CounterApplyConfiguration struct {
	Value *string `json:"value,omitempty"`
}

// CounterApplyConfiguration constructs an declarative configuration of the Counter type for use with
// apply.
func Counter() *CounterApplyConfiguration {
	return &CounterApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *CounterApplyConfiguration) WithValue(value string) *CounterApplyConfiguration {
	b.Value = &value
	return b
}
