// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
)

// HistogramApplyConfiguration represents an declarative configuration of the Histogram type for use
// with apply.
type HistogramApplyConfiguration struct {
	Value   *string           `json:"value,omitempty"`
	Buckets []v1alpha1.Amount `json:"buckets,omitempty"`
}

// HistogramApplyConfiguration constructs an declarative configuration of the Histogram type for use with
// apply.
func Histogram() *HistogramApplyConfiguration {
	return &HistogramApplyConfiguration{}
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *HistogramApplyConfiguration) WithValue(value string) *HistogramApplyConfiguration {
	b.Value = &value
	return b
}

// WithBuckets adds the given value to the Buckets field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Buckets field.
func (b *HistogramApplyConfiguration) WithBuckets(values ...v1alpha1.Amount) *HistogramApplyConfiguration {
	for i := range values {
		b.Buckets = append(b.Buckets, values[i])
	}
	return b
}
