// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// HTTPBodySourceApplyConfiguration represents an declarative configuration of the HTTPBodySource type for use
// with apply.
type HTTPBodySourceApplyConfiguration struct {
	Bytes []byte `json:"bytes,omitempty"`
}

// HTTPBodySourceApplyConfiguration constructs an declarative configuration of the HTTPBodySource type for use with
// apply.
func HTTPBodySource() *HTTPBodySourceApplyConfiguration {
	return &HTTPBodySourceApplyConfiguration{}
}

// WithBytes adds the given value to the Bytes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Bytes field.
func (b *HTTPBodySourceApplyConfiguration) WithBytes(values ...byte) *HTTPBodySourceApplyConfiguration {
	for i := range values {
		b.Bytes = append(b.Bytes, values[i])
	}
	return b
}
