// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// LabelValueFromApplyConfiguration represents an declarative configuration of the LabelValueFrom type for use
// with apply.
type LabelValueFromApplyConfiguration struct {
	Expression *string `json:"expression,omitempty"`
}

// LabelValueFromApplyConfiguration constructs an declarative configuration of the LabelValueFrom type for use with
// apply.
func LabelValueFrom() *LabelValueFromApplyConfiguration {
	return &LabelValueFromApplyConfiguration{}
}

// WithExpression sets the Expression field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Expression field is set to the value of the last call.
func (b *LabelValueFromApplyConfiguration) WithExpression(value string) *LabelValueFromApplyConfiguration {
	b.Expression = &value
	return b
}
