// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// MutexApplyConfiguration represents an declarative configuration of the Mutex type for use
// with apply.
type MutexApplyConfiguration struct {
	Name      *string `json:"name,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// MutexApplyConfiguration constructs an declarative configuration of the Mutex type for use with
// apply.
func Mutex() *MutexApplyConfiguration {
	return &MutexApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *MutexApplyConfiguration) WithName(value string) *MutexApplyConfiguration {
	b.Name = &value
	return b
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *MutexApplyConfiguration) WithNamespace(value string) *MutexApplyConfiguration {
	b.Namespace = &value
	return b
}
