// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/core/v1"
)

// OSSArtifactRepositoryApplyConfiguration represents an declarative configuration of the OSSArtifactRepository type for use
// with apply.
type OSSArtifactRepositoryApplyConfiguration struct {
	OSSBucketApplyConfiguration `json:",inline"`
	KeyFormat                   *string `json:"keyFormat,omitempty"`
}

// OSSArtifactRepositoryApplyConfiguration constructs an declarative configuration of the OSSArtifactRepository type for use with
// apply.
func OSSArtifactRepository() *OSSArtifactRepositoryApplyConfiguration {
	return &OSSArtifactRepositoryApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithEndpoint(value string) *OSSArtifactRepositoryApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithBucket(value string) *OSSArtifactRepositoryApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithAccessKeySecret sets the AccessKeySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKeySecret field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithAccessKeySecret(value *v1.SecretKeySelectorApplyConfiguration) *OSSArtifactRepositoryApplyConfiguration {
	b.AccessKeySecret = value
	return b
}

// WithSecretKeySecret sets the SecretKeySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretKeySecret field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithSecretKeySecret(value *v1.SecretKeySelectorApplyConfiguration) *OSSArtifactRepositoryApplyConfiguration {
	b.SecretKeySecret = value
	return b
}

// WithCreateBucketIfNotPresent sets the CreateBucketIfNotPresent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateBucketIfNotPresent field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithCreateBucketIfNotPresent(value bool) *OSSArtifactRepositoryApplyConfiguration {
	b.CreateBucketIfNotPresent = &value
	return b
}

// WithSecurityToken sets the SecurityToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecurityToken field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithSecurityToken(value string) *OSSArtifactRepositoryApplyConfiguration {
	b.SecurityToken = &value
	return b
}

// WithLifecycleRule sets the LifecycleRule field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LifecycleRule field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithLifecycleRule(value *OSSLifecycleRuleApplyConfiguration) *OSSArtifactRepositoryApplyConfiguration {
	b.LifecycleRule = value
	return b
}

// WithUseSDKCreds sets the UseSDKCreds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseSDKCreds field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithUseSDKCreds(value bool) *OSSArtifactRepositoryApplyConfiguration {
	b.UseSDKCreds = &value
	return b
}

// WithKeyFormat sets the KeyFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyFormat field is set to the value of the last call.
func (b *OSSArtifactRepositoryApplyConfiguration) WithKeyFormat(value string) *OSSArtifactRepositoryApplyConfiguration {
	b.KeyFormat = &value
	return b
}
