// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
)

// PluginApplyConfiguration represents an declarative configuration of the Plugin type for use
// with apply.
type PluginApplyConfiguration struct {
	v1alpha1.Object `json:",inline"`
}

// PluginApplyConfiguration constructs an declarative configuration of the Plugin type for use with
// apply.
func Plugin() *PluginApplyConfiguration {
	return &PluginApplyConfiguration{}
}
