// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// PodGCApplyConfiguration represents an declarative configuration of the PodGC type for use
// with apply.
type PodGCApplyConfiguration struct {
	Strategy            *v1alpha1.PodGCStrategy             `json:"strategy,omitempty"`
	LabelSelector       *v1.LabelSelectorApplyConfiguration `json:"labelSelector,omitempty"`
	DeleteDelayDuration *metav1.Duration                    `json:"deleteDelayDuration,omitempty"`
}

// PodGCApplyConfiguration constructs an declarative configuration of the PodGC type for use with
// apply.
func PodGC() *PodGCApplyConfiguration {
	return &PodGCApplyConfiguration{}
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *PodGCApplyConfiguration) WithStrategy(value v1alpha1.PodGCStrategy) *PodGCApplyConfiguration {
	b.Strategy = &value
	return b
}

// WithLabelSelector sets the LabelSelector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LabelSelector field is set to the value of the last call.
func (b *PodGCApplyConfiguration) WithLabelSelector(value *v1.LabelSelectorApplyConfiguration) *PodGCApplyConfiguration {
	b.LabelSelector = value
	return b
}

// WithDeleteDelayDuration sets the DeleteDelayDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DeleteDelayDuration field is set to the value of the last call.
func (b *PodGCApplyConfiguration) WithDeleteDelayDuration(value metav1.Duration) *PodGCApplyConfiguration {
	b.DeleteDelayDuration = &value
	return b
}
