// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// RawArtifactApplyConfiguration represents an declarative configuration of the RawArtifact type for use
// with apply.
type RawArtifactApplyConfiguration struct {
	Data *string `json:"data,omitempty"`
}

// RawArtifactApplyConfiguration constructs an declarative configuration of the RawArtifact type for use with
// apply.
func RawArtifact() *RawArtifactApplyConfiguration {
	return &RawArtifactApplyConfiguration{}
}

// WithData sets the Data field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Data field is set to the value of the last call.
func (b *RawArtifactApplyConfiguration) WithData(value string) *RawArtifactApplyConfiguration {
	b.Data = &value
	return b
}
