// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/core/v1"
)

// S3ArtifactRepositoryApplyConfiguration represents an declarative configuration of the S3ArtifactRepository type for use
// with apply.
type S3ArtifactRepositoryApplyConfiguration struct {
	S3BucketApplyConfiguration `json:",inline"`
	KeyFormat                  *string `json:"keyFormat,omitempty"`
	KeyPrefix                  *string `json:"keyPrefix,omitempty"`
}

// S3ArtifactRepositoryApplyConfiguration constructs an declarative configuration of the S3ArtifactRepository type for use with
// apply.
func S3ArtifactRepository() *S3ArtifactRepositoryApplyConfiguration {
	return &S3ArtifactRepositoryApplyConfiguration{}
}

// WithEndpoint sets the Endpoint field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Endpoint field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithEndpoint(value string) *S3ArtifactRepositoryApplyConfiguration {
	b.Endpoint = &value
	return b
}

// WithBucket sets the Bucket field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Bucket field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithBucket(value string) *S3ArtifactRepositoryApplyConfiguration {
	b.Bucket = &value
	return b
}

// WithRegion sets the Region field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Region field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithRegion(value string) *S3ArtifactRepositoryApplyConfiguration {
	b.Region = &value
	return b
}

// WithInsecure sets the Insecure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Insecure field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithInsecure(value bool) *S3ArtifactRepositoryApplyConfiguration {
	b.Insecure = &value
	return b
}

// WithAccessKeySecret sets the AccessKeySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the AccessKeySecret field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithAccessKeySecret(value *v1.SecretKeySelectorApplyConfiguration) *S3ArtifactRepositoryApplyConfiguration {
	b.AccessKeySecret = value
	return b
}

// WithSecretKeySecret sets the SecretKeySecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretKeySecret field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithSecretKeySecret(value *v1.SecretKeySelectorApplyConfiguration) *S3ArtifactRepositoryApplyConfiguration {
	b.SecretKeySecret = value
	return b
}

// WithRoleARN sets the RoleARN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RoleARN field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithRoleARN(value string) *S3ArtifactRepositoryApplyConfiguration {
	b.RoleARN = &value
	return b
}

// WithUseSDKCreds sets the UseSDKCreds field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UseSDKCreds field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithUseSDKCreds(value bool) *S3ArtifactRepositoryApplyConfiguration {
	b.UseSDKCreds = &value
	return b
}

// WithCreateBucketIfNotPresent sets the CreateBucketIfNotPresent field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CreateBucketIfNotPresent field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithCreateBucketIfNotPresent(value *CreateS3BucketOptionsApplyConfiguration) *S3ArtifactRepositoryApplyConfiguration {
	b.CreateBucketIfNotPresent = value
	return b
}

// WithEncryptionOptions sets the EncryptionOptions field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EncryptionOptions field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithEncryptionOptions(value *S3EncryptionOptionsApplyConfiguration) *S3ArtifactRepositoryApplyConfiguration {
	b.EncryptionOptions = value
	return b
}

// WithCASecret sets the CASecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the CASecret field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithCASecret(value *v1.SecretKeySelectorApplyConfiguration) *S3ArtifactRepositoryApplyConfiguration {
	b.CASecret = value
	return b
}

// WithKeyFormat sets the KeyFormat field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyFormat field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithKeyFormat(value string) *S3ArtifactRepositoryApplyConfiguration {
	b.KeyFormat = &value
	return b
}

// WithKeyPrefix sets the KeyPrefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the KeyPrefix field is set to the value of the last call.
func (b *S3ArtifactRepositoryApplyConfiguration) WithKeyPrefix(value string) *S3ArtifactRepositoryApplyConfiguration {
	b.KeyPrefix = &value
	return b
}
