// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// TTLStrategyApplyConfiguration represents an declarative configuration of the TTLStrategy type for use
// with apply.
type TTLStrategyApplyConfiguration struct {
	SecondsAfterCompletion *int32 `json:"secondsAfterCompletion,omitempty"`
	SecondsAfterSuccess    *int32 `json:"secondsAfterSuccess,omitempty"`
	SecondsAfterFailure    *int32 `json:"secondsAfterFailure,omitempty"`
}

// TTLStrategyApplyConfiguration constructs an declarative configuration of the TTLStrategy type for use with
// apply.
func TTLStrategy() *TTLStrategyApplyConfiguration {
	return &TTLStrategyApplyConfiguration{}
}

// WithSecondsAfterCompletion sets the SecondsAfterCompletion field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecondsAfterCompletion field is set to the value of the last call.
func (b *TTLStrategyApplyConfiguration) WithSecondsAfterCompletion(value int32) *TTLStrategyApplyConfiguration {
	b.SecondsAfterCompletion = &value
	return b
}

// WithSecondsAfterSuccess sets the SecondsAfterSuccess field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecondsAfterSuccess field is set to the value of the last call.
func (b *TTLStrategyApplyConfiguration) WithSecondsAfterSuccess(value int32) *TTLStrategyApplyConfiguration {
	b.SecondsAfterSuccess = &value
	return b
}

// WithSecondsAfterFailure sets the SecondsAfterFailure field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecondsAfterFailure field is set to the value of the last call.
func (b *TTLStrategyApplyConfiguration) WithSecondsAfterFailure(value int32) *TTLStrategyApplyConfiguration {
	b.SecondsAfterFailure = &value
	return b
}
