// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/argoproj/argo-workflows/v3/pkg/apis/workflow/v1alpha1"
)

// VolumeClaimGCApplyConfiguration represents an declarative configuration of the VolumeClaimGC type for use
// with apply.
type VolumeClaimGCApplyConfiguration struct {
	Strategy *v1alpha1.VolumeClaimGCStrategy `json:"strategy,omitempty"`
}

// VolumeClaimGCApplyConfiguration constructs an declarative configuration of the VolumeClaimGC type for use with
// apply.
func VolumeClaimGC() *VolumeClaimGCApplyConfiguration {
	return &VolumeClaimGCApplyConfiguration{}
}

// WithStrategy sets the Strategy field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Strategy field is set to the value of the last call.
func (b *VolumeClaimGCApplyConfiguration) WithStrategy(value v1alpha1.VolumeClaimGCStrategy) *VolumeClaimGCApplyConfiguration {
	b.Strategy = &value
	return b
}
