// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// ConditionSummaryApplyConfiguration represents an declarative configuration of the ConditionSummary type for use
// with apply.
type ConditionSummaryApplyConfiguration struct {
	Phase        *string `json:"phase,omitempty"`
	PhaseMessage *string `json:"phaseMessage,omitempty"`
}

// ConditionSummaryApplyConfiguration constructs an declarative configuration of the ConditionSummary type for use with
// apply.
func ConditionSummary() *ConditionSummaryApplyConfiguration {
	return &ConditionSummaryApplyConfiguration{}
}

// WithPhase sets the Phase field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Phase field is set to the value of the last call.
func (b *ConditionSummaryApplyConfiguration) WithPhase(value string) *ConditionSummaryApplyConfiguration {
	b.Phase = &value
	return b
}

// WithPhaseMessage sets the PhaseMessage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PhaseMessage field is set to the value of the last call.
func (b *ConditionSummaryApplyConfiguration) WithPhaseMessage(value string) *ConditionSummaryApplyConfiguration {
	b.PhaseMessage = &value
	return b
}
