// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// ResourceDefinitionMatchingRuleReferenceApplyConfiguration represents an declarative configuration of the ResourceDefinitionMatchingRuleReference type for use
// with apply.
type ResourceDefinitionMatchingRuleReferenceApplyConfiguration struct {
	Namespace *string `json:"namespace,omitempty"`
	Name      *string `json:"name,omitempty"`
}

// ResourceDefinitionMatchingRuleReferenceApplyConfiguration constructs an declarative configuration of the ResourceDefinitionMatchingRuleReference type for use with
// apply.
func ResourceDefinitionMatchingRuleReference() *ResourceDefinitionMatchingRuleReferenceApplyConfiguration {
	return &ResourceDefinitionMatchingRuleReferenceApplyConfiguration{}
}

// WithNamespace sets the Namespace field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Namespace field is set to the value of the last call.
func (b *ResourceDefinitionMatchingRuleReferenceApplyConfiguration) WithNamespace(value string) *ResourceDefinitionMatchingRuleReferenceApplyConfiguration {
	b.Namespace = &value
	return b
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *ResourceDefinitionMatchingRuleReferenceApplyConfiguration) WithName(value string) *ResourceDefinitionMatchingRuleReferenceApplyConfiguration {
	b.Name = &value
	return b
}
