// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/seal-io/walrus/pkg/apis/walrus/v1"
	walrusv1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walrus/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeSchemas implements SchemaInterface
type FakeSchemas struct {
	Fake *FakeWalrusV1
	ns   string
}

var schemasResource = v1.SchemeGroupVersion.WithResource("schemas")

var schemasKind = v1.SchemeGroupVersion.WithKind("Schema")

// Get takes name of the schema, and returns the corresponding schema object, and an error if there is any.
func (c *FakeSchemas) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.Schema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(schemasResource, c.ns, name), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}

// List takes label and field selectors, and returns the list of Schemas that match those selectors.
func (c *FakeSchemas) List(ctx context.Context, opts metav1.ListOptions) (result *v1.SchemaList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(schemasResource, schemasKind, c.ns, opts), &v1.SchemaList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.SchemaList{ListMeta: obj.(*v1.SchemaList).ListMeta}
	for _, item := range obj.(*v1.SchemaList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested schemas.
func (c *FakeSchemas) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(schemasResource, c.ns, opts))

}

// Create takes the representation of a schema and creates it.  Returns the server's representation of the schema, and an error, if there is any.
func (c *FakeSchemas) Create(ctx context.Context, schema *v1.Schema, opts metav1.CreateOptions) (result *v1.Schema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(schemasResource, c.ns, schema), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}

// Update takes the representation of a schema and updates it. Returns the server's representation of the schema, and an error, if there is any.
func (c *FakeSchemas) Update(ctx context.Context, schema *v1.Schema, opts metav1.UpdateOptions) (result *v1.Schema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(schemasResource, c.ns, schema), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeSchemas) UpdateStatus(ctx context.Context, schema *v1.Schema, opts metav1.UpdateOptions) (*v1.Schema, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(schemasResource, "status", c.ns, schema), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}

// Delete takes name of the schema and deletes it. Returns an error if one occurs.
func (c *FakeSchemas) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(schemasResource, c.ns, name, opts), &v1.Schema{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeSchemas) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(schemasResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.SchemaList{})
	return err
}

// Patch applies the patch and returns the patched schema.
func (c *FakeSchemas) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.Schema, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(schemasResource, c.ns, name, pt, data, subresources...), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied schema.
func (c *FakeSchemas) Apply(ctx context.Context, schema *walrusv1.SchemaApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Schema, err error) {
	if schema == nil {
		return nil, fmt.Errorf("schema provided to Apply must not be nil")
	}
	data, err := json.Marshal(schema)
	if err != nil {
		return nil, err
	}
	name := schema.Name
	if name == nil {
		return nil, fmt.Errorf("schema.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(schemasResource, c.ns, *name, types.ApplyPatchType, data), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeSchemas) ApplyStatus(ctx context.Context, schema *walrusv1.SchemaApplyConfiguration, opts metav1.ApplyOptions) (result *v1.Schema, err error) {
	if schema == nil {
		return nil, fmt.Errorf("schema provided to Apply must not be nil")
	}
	data, err := json.Marshal(schema)
	if err != nil {
		return nil, err
	}
	name := schema.Name
	if name == nil {
		return nil, fmt.Errorf("schema.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(schemasResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.Schema{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.Schema), err
}
