// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1 "github.com/seal-io/walrus/pkg/apis/walruscore/v1"
	walruscorev1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walruscore/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeResourceRunStepTemplates implements ResourceRunStepTemplateInterface
type FakeResourceRunStepTemplates struct {
	Fake *FakeWalruscoreV1
	ns   string
}

var resourcerunsteptemplatesResource = v1.SchemeGroupVersion.WithResource("resourcerunsteptemplates")

var resourcerunsteptemplatesKind = v1.SchemeGroupVersion.WithKind("ResourceRunStepTemplate")

// Get takes name of the resourceRunStepTemplate, and returns the corresponding resourceRunStepTemplate object, and an error if there is any.
func (c *FakeResourceRunStepTemplates) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ResourceRunStepTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(resourcerunsteptemplatesResource, c.ns, name), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}

// List takes label and field selectors, and returns the list of ResourceRunStepTemplates that match those selectors.
func (c *FakeResourceRunStepTemplates) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ResourceRunStepTemplateList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(resourcerunsteptemplatesResource, resourcerunsteptemplatesKind, c.ns, opts), &v1.ResourceRunStepTemplateList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1.ResourceRunStepTemplateList{ListMeta: obj.(*v1.ResourceRunStepTemplateList).ListMeta}
	for _, item := range obj.(*v1.ResourceRunStepTemplateList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested resourceRunStepTemplates.
func (c *FakeResourceRunStepTemplates) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(resourcerunsteptemplatesResource, c.ns, opts))

}

// Create takes the representation of a resourceRunStepTemplate and creates it.  Returns the server's representation of the resourceRunStepTemplate, and an error, if there is any.
func (c *FakeResourceRunStepTemplates) Create(ctx context.Context, resourceRunStepTemplate *v1.ResourceRunStepTemplate, opts metav1.CreateOptions) (result *v1.ResourceRunStepTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(resourcerunsteptemplatesResource, c.ns, resourceRunStepTemplate), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}

// Update takes the representation of a resourceRunStepTemplate and updates it. Returns the server's representation of the resourceRunStepTemplate, and an error, if there is any.
func (c *FakeResourceRunStepTemplates) Update(ctx context.Context, resourceRunStepTemplate *v1.ResourceRunStepTemplate, opts metav1.UpdateOptions) (result *v1.ResourceRunStepTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(resourcerunsteptemplatesResource, c.ns, resourceRunStepTemplate), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeResourceRunStepTemplates) UpdateStatus(ctx context.Context, resourceRunStepTemplate *v1.ResourceRunStepTemplate, opts metav1.UpdateOptions) (*v1.ResourceRunStepTemplate, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(resourcerunsteptemplatesResource, "status", c.ns, resourceRunStepTemplate), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}

// Delete takes name of the resourceRunStepTemplate and deletes it. Returns an error if one occurs.
func (c *FakeResourceRunStepTemplates) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(resourcerunsteptemplatesResource, c.ns, name, opts), &v1.ResourceRunStepTemplate{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeResourceRunStepTemplates) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(resourcerunsteptemplatesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1.ResourceRunStepTemplateList{})
	return err
}

// Patch applies the patch and returns the patched resourceRunStepTemplate.
func (c *FakeResourceRunStepTemplates) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceRunStepTemplate, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcerunsteptemplatesResource, c.ns, name, pt, data, subresources...), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied resourceRunStepTemplate.
func (c *FakeResourceRunStepTemplates) Apply(ctx context.Context, resourceRunStepTemplate *walruscorev1.ResourceRunStepTemplateApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceRunStepTemplate, err error) {
	if resourceRunStepTemplate == nil {
		return nil, fmt.Errorf("resourceRunStepTemplate provided to Apply must not be nil")
	}
	data, err := json.Marshal(resourceRunStepTemplate)
	if err != nil {
		return nil, err
	}
	name := resourceRunStepTemplate.Name
	if name == nil {
		return nil, fmt.Errorf("resourceRunStepTemplate.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcerunsteptemplatesResource, c.ns, *name, types.ApplyPatchType, data), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeResourceRunStepTemplates) ApplyStatus(ctx context.Context, resourceRunStepTemplate *walruscorev1.ResourceRunStepTemplateApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceRunStepTemplate, err error) {
	if resourceRunStepTemplate == nil {
		return nil, fmt.Errorf("resourceRunStepTemplate provided to Apply must not be nil")
	}
	data, err := json.Marshal(resourceRunStepTemplate)
	if err != nil {
		return nil, err
	}
	name := resourceRunStepTemplate.Name
	if name == nil {
		return nil, fmt.Errorf("resourceRunStepTemplate.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(resourcerunsteptemplatesResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1.ResourceRunStepTemplate{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1.ResourceRunStepTemplate), err
}
