// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SubjectProviderLDAPConfigApplyConfiguration represents an declarative configuration of the SubjectProviderLDAPConfig type for use
// with apply.
type SubjectProviderLDAPConfigApplyConfiguration struct {
	Host                   *string                                           `json:"host,omitempty"`
	SkipInsecureVerify     *bool                                             `json:"skipInsecureVerify,omitempty"`
	ServiceAccountDN       *string                                           `json:"serviceAccountDN,omitempty"`
	ServiceAccountPassword *string                                           `json:"serviceAccountPassword,omitempty"`
	GroupSearch            *SubjectProviderLdapGroupSearchApplyConfiguration `json:"groupSearch,omitempty"`
	UserSearch             *SubjectProviderLdapUserSearchApplyConfiguration  `json:"userSearch,omitempty"`
}

// SubjectProviderLDAPConfigApplyConfiguration constructs an declarative configuration of the SubjectProviderLDAPConfig type for use with
// apply.
func SubjectProviderLDAPConfig() *SubjectProviderLDAPConfigApplyConfiguration {
	return &SubjectProviderLDAPConfigApplyConfiguration{}
}

// WithHost sets the Host field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Host field is set to the value of the last call.
func (b *SubjectProviderLDAPConfigApplyConfiguration) WithHost(value string) *SubjectProviderLDAPConfigApplyConfiguration {
	b.Host = &value
	return b
}

// WithSkipInsecureVerify sets the SkipInsecureVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipInsecureVerify field is set to the value of the last call.
func (b *SubjectProviderLDAPConfigApplyConfiguration) WithSkipInsecureVerify(value bool) *SubjectProviderLDAPConfigApplyConfiguration {
	b.SkipInsecureVerify = &value
	return b
}

// WithServiceAccountDN sets the ServiceAccountDN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountDN field is set to the value of the last call.
func (b *SubjectProviderLDAPConfigApplyConfiguration) WithServiceAccountDN(value string) *SubjectProviderLDAPConfigApplyConfiguration {
	b.ServiceAccountDN = &value
	return b
}

// WithServiceAccountPassword sets the ServiceAccountPassword field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ServiceAccountPassword field is set to the value of the last call.
func (b *SubjectProviderLDAPConfigApplyConfiguration) WithServiceAccountPassword(value string) *SubjectProviderLDAPConfigApplyConfiguration {
	b.ServiceAccountPassword = &value
	return b
}

// WithGroupSearch sets the GroupSearch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GroupSearch field is set to the value of the last call.
func (b *SubjectProviderLDAPConfigApplyConfiguration) WithGroupSearch(value *SubjectProviderLdapGroupSearchApplyConfiguration) *SubjectProviderLDAPConfigApplyConfiguration {
	b.GroupSearch = value
	return b
}

// WithUserSearch sets the UserSearch field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the UserSearch field is set to the value of the last call.
func (b *SubjectProviderLDAPConfigApplyConfiguration) WithUserSearch(value *SubjectProviderLdapUserSearchApplyConfiguration) *SubjectProviderLDAPConfigApplyConfiguration {
	b.UserSearch = value
	return b
}
