// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SubjectProviderLDAPUserSearchApplyConfiguration represents an declarative configuration of the SubjectProviderLDAPUserSearch type for use
// with apply.
type SubjectProviderLDAPUserSearchApplyConfiguration struct {
	BaseDN               *string `json:"baseDN,omitempty"`
	Filter               *string `json:"filter,omitempty"`
	NameAttribute        *string `json:"nameAttribute,omitempty"`
	DisplayNameAttribute *string `json:"displayNameAttribute,omitempty"`
	EmailAttribute       *string `json:"emailAttribute,omitempty"`
}

// SubjectProviderLDAPUserSearchApplyConfiguration constructs an declarative configuration of the SubjectProviderLDAPUserSearch type for use with
// apply.
func SubjectProviderLDAPUserSearch() *SubjectProviderLDAPUserSearchApplyConfiguration {
	return &SubjectProviderLDAPUserSearchApplyConfiguration{}
}

// WithBaseDN sets the BaseDN field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BaseDN field is set to the value of the last call.
func (b *SubjectProviderLDAPUserSearchApplyConfiguration) WithBaseDN(value string) *SubjectProviderLDAPUserSearchApplyConfiguration {
	b.BaseDN = &value
	return b
}

// WithFilter sets the Filter field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Filter field is set to the value of the last call.
func (b *SubjectProviderLDAPUserSearchApplyConfiguration) WithFilter(value string) *SubjectProviderLDAPUserSearchApplyConfiguration {
	b.Filter = &value
	return b
}

// WithNameAttribute sets the NameAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the NameAttribute field is set to the value of the last call.
func (b *SubjectProviderLDAPUserSearchApplyConfiguration) WithNameAttribute(value string) *SubjectProviderLDAPUserSearchApplyConfiguration {
	b.NameAttribute = &value
	return b
}

// WithDisplayNameAttribute sets the DisplayNameAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DisplayNameAttribute field is set to the value of the last call.
func (b *SubjectProviderLDAPUserSearchApplyConfiguration) WithDisplayNameAttribute(value string) *SubjectProviderLDAPUserSearchApplyConfiguration {
	b.DisplayNameAttribute = &value
	return b
}

// WithEmailAttribute sets the EmailAttribute field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the EmailAttribute field is set to the value of the last call.
func (b *SubjectProviderLDAPUserSearchApplyConfiguration) WithEmailAttribute(value string) *SubjectProviderLDAPUserSearchApplyConfiguration {
	b.EmailAttribute = &value
	return b
}
