// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

// SubjectProviderOIDCConfigApplyConfiguration represents an declarative configuration of the SubjectProviderOIDCConfig type for use
// with apply.
type SubjectProviderOIDCConfigApplyConfiguration struct {
	Issuer             *string                                             `json:"issuer,omitempty"`
	SkipInsecureVerify *bool                                               `json:"skipInsecureVerify,omitempty"`
	ClientID           *string                                             `json:"clientID,omitempty"`
	ClientSecret       *string                                             `json:"clientSecret,omitempty"`
	ClaimMapping       *SubjectProviderOAuthClaimMappingApplyConfiguration `json:"claimMapping,omitempty"`
}

// SubjectProviderOIDCConfigApplyConfiguration constructs an declarative configuration of the SubjectProviderOIDCConfig type for use with
// apply.
func SubjectProviderOIDCConfig() *SubjectProviderOIDCConfigApplyConfiguration {
	return &SubjectProviderOIDCConfigApplyConfiguration{}
}

// WithIssuer sets the Issuer field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Issuer field is set to the value of the last call.
func (b *SubjectProviderOIDCConfigApplyConfiguration) WithIssuer(value string) *SubjectProviderOIDCConfigApplyConfiguration {
	b.Issuer = &value
	return b
}

// WithSkipInsecureVerify sets the SkipInsecureVerify field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SkipInsecureVerify field is set to the value of the last call.
func (b *SubjectProviderOIDCConfigApplyConfiguration) WithSkipInsecureVerify(value bool) *SubjectProviderOIDCConfigApplyConfiguration {
	b.SkipInsecureVerify = &value
	return b
}

// WithClientID sets the ClientID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientID field is set to the value of the last call.
func (b *SubjectProviderOIDCConfigApplyConfiguration) WithClientID(value string) *SubjectProviderOIDCConfigApplyConfiguration {
	b.ClientID = &value
	return b
}

// WithClientSecret sets the ClientSecret field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClientSecret field is set to the value of the last call.
func (b *SubjectProviderOIDCConfigApplyConfiguration) WithClientSecret(value string) *SubjectProviderOIDCConfigApplyConfiguration {
	b.ClientSecret = &value
	return b
}

// WithClaimMapping sets the ClaimMapping field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClaimMapping field is set to the value of the last call.
func (b *SubjectProviderOIDCConfigApplyConfiguration) WithClaimMapping(value *SubjectProviderOAuthClaimMappingApplyConfiguration) *SubjectProviderOIDCConfigApplyConfiguration {
	b.ClaimMapping = value
	return b
}
