// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

type ClusterWorkflowTemplateExpansion interface{}

type CronWorkflowExpansion interface{}

type WorkflowExpansion interface{}

type WorkflowArtifactGCTaskExpansion interface{}

type WorkflowEventBindingExpansion interface{}

type WorkflowTaskResultExpansion interface{}

type WorkflowTaskSetExpansion interface{}

type WorkflowTemplateExpansion interface{}
