// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

// ApplicationSetGeneratorApplyConfiguration represents an declarative configuration of the ApplicationSetGenerator type for use
// with apply.
type ApplicationSetGeneratorApplyConfiguration struct {
	List                    *ListGeneratorApplyConfiguration        `json:"list,omitempty"`
	Clusters                *ClusterGeneratorApplyConfiguration     `json:"clusters,omitempty"`
	Git                     *GitGeneratorApplyConfiguration         `json:"git,omitempty"`
	SCMProvider             *SCMProviderGeneratorApplyConfiguration `json:"scmProvider,omitempty"`
	ClusterDecisionResource *DuckTypeGeneratorApplyConfiguration    `json:"clusterDecisionResource,omitempty"`
	PullRequest             *PullRequestGeneratorApplyConfiguration `json:"pullRequest,omitempty"`
	Matrix                  *MatrixGeneratorApplyConfiguration      `json:"matrix,omitempty"`
	Merge                   *MergeGeneratorApplyConfiguration       `json:"merge,omitempty"`
	Selector                *v1.LabelSelectorApplyConfiguration     `json:"selector,omitempty"`
	Plugin                  *PluginGeneratorApplyConfiguration      `json:"plugin,omitempty"`
}

// ApplicationSetGeneratorApplyConfiguration constructs an declarative configuration of the ApplicationSetGenerator type for use with
// apply.
func ApplicationSetGenerator() *ApplicationSetGeneratorApplyConfiguration {
	return &ApplicationSetGeneratorApplyConfiguration{}
}

// WithList sets the List field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the List field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithList(value *ListGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.List = value
	return b
}

// WithClusters sets the Clusters field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Clusters field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithClusters(value *ClusterGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.Clusters = value
	return b
}

// WithGit sets the Git field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Git field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithGit(value *GitGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.Git = value
	return b
}

// WithSCMProvider sets the SCMProvider field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SCMProvider field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithSCMProvider(value *SCMProviderGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.SCMProvider = value
	return b
}

// WithClusterDecisionResource sets the ClusterDecisionResource field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ClusterDecisionResource field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithClusterDecisionResource(value *DuckTypeGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.ClusterDecisionResource = value
	return b
}

// WithPullRequest sets the PullRequest field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the PullRequest field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithPullRequest(value *PullRequestGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.PullRequest = value
	return b
}

// WithMatrix sets the Matrix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Matrix field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithMatrix(value *MatrixGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.Matrix = value
	return b
}

// WithMerge sets the Merge field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Merge field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithMerge(value *MergeGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.Merge = value
	return b
}

// WithSelector sets the Selector field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Selector field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithSelector(value *v1.LabelSelectorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.Selector = value
	return b
}

// WithPlugin sets the Plugin field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Plugin field is set to the value of the last call.
func (b *ApplicationSetGeneratorApplyConfiguration) WithPlugin(value *PluginGeneratorApplyConfiguration) *ApplicationSetGeneratorApplyConfiguration {
	b.Plugin = value
	return b
}
