// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// ApplicationSourceDirectoryApplyConfiguration represents an declarative configuration of the ApplicationSourceDirectory type for use
// with apply.
type ApplicationSourceDirectoryApplyConfiguration struct {
	Recurse *bool                                       `json:"recurse,omitempty"`
	Jsonnet *ApplicationSourceJsonnetApplyConfiguration `json:"jsonnet,omitempty"`
	Exclude *string                                     `json:"exclude,omitempty"`
	Include *string                                     `json:"include,omitempty"`
}

// ApplicationSourceDirectoryApplyConfiguration constructs an declarative configuration of the ApplicationSourceDirectory type for use with
// apply.
func ApplicationSourceDirectory() *ApplicationSourceDirectoryApplyConfiguration {
	return &ApplicationSourceDirectoryApplyConfiguration{}
}

// WithRecurse sets the Recurse field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Recurse field is set to the value of the last call.
func (b *ApplicationSourceDirectoryApplyConfiguration) WithRecurse(value bool) *ApplicationSourceDirectoryApplyConfiguration {
	b.Recurse = &value
	return b
}

// WithJsonnet sets the Jsonnet field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Jsonnet field is set to the value of the last call.
func (b *ApplicationSourceDirectoryApplyConfiguration) WithJsonnet(value *ApplicationSourceJsonnetApplyConfiguration) *ApplicationSourceDirectoryApplyConfiguration {
	b.Jsonnet = value
	return b
}

// WithExclude sets the Exclude field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Exclude field is set to the value of the last call.
func (b *ApplicationSourceDirectoryApplyConfiguration) WithExclude(value string) *ApplicationSourceDirectoryApplyConfiguration {
	b.Exclude = &value
	return b
}

// WithInclude sets the Include field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Include field is set to the value of the last call.
func (b *ApplicationSourceDirectoryApplyConfiguration) WithInclude(value string) *ApplicationSourceDirectoryApplyConfiguration {
	b.Include = &value
	return b
}
