// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// ApplicationSetRolloutStrategyApplyConfiguration represents an declarative configuration of the ApplicationSetRolloutStrategy type for use
// with apply.
type ApplicationSetRolloutStrategyApplyConfiguration struct {
	Steps []ApplicationSetRolloutStepApplyConfiguration `json:"steps,omitempty"`
}

// ApplicationSetRolloutStrategyApplyConfiguration constructs an declarative configuration of the ApplicationSetRolloutStrategy type for use with
// apply.
func ApplicationSetRolloutStrategy() *ApplicationSetRolloutStrategyApplyConfiguration {
	return &ApplicationSetRolloutStrategyApplyConfiguration{}
}

// WithSteps adds the given value to the Steps field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Steps field.
func (b *ApplicationSetRolloutStrategyApplyConfiguration) WithSteps(values ...*ApplicationSetRolloutStepApplyConfiguration) *ApplicationSetRolloutStrategyApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithSteps")
		}
		b.Steps = append(b.Steps, *values[i])
	}
	return b
}
