// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// HelmFileParameterApplyConfiguration represents an declarative configuration of the HelmFileParameter type for use
// with apply.
type HelmFileParameterApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
	Path *string `json:"path,omitempty"`
}

// HelmFileParameterApplyConfiguration constructs an declarative configuration of the HelmFileParameter type for use with
// apply.
func HelmFileParameter() *HelmFileParameterApplyConfiguration {
	return &HelmFileParameterApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *HelmFileParameterApplyConfiguration) WithName(value string) *HelmFileParameterApplyConfiguration {
	b.Name = &value
	return b
}

// WithPath sets the Path field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Path field is set to the value of the last call.
func (b *HelmFileParameterApplyConfiguration) WithPath(value string) *HelmFileParameterApplyConfiguration {
	b.Path = &value
	return b
}
