// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// JsonnetVarApplyConfiguration represents an declarative configuration of the JsonnetVar type for use
// with apply.
type JsonnetVarApplyConfiguration struct {
	Name  *string `json:"name,omitempty"`
	Value *string `json:"value,omitempty"`
	Code  *bool   `json:"code,omitempty"`
}

// JsonnetVarApplyConfiguration constructs an declarative configuration of the JsonnetVar type for use with
// apply.
func JsonnetVar() *JsonnetVarApplyConfiguration {
	return &JsonnetVarApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JsonnetVarApplyConfiguration) WithName(value string) *JsonnetVarApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *JsonnetVarApplyConfiguration) WithValue(value string) *JsonnetVarApplyConfiguration {
	b.Value = &value
	return b
}

// WithCode sets the Code field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Code field is set to the value of the last call.
func (b *JsonnetVarApplyConfiguration) WithCode(value bool) *JsonnetVarApplyConfiguration {
	b.Code = &value
	return b
}
