// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// JWTTokenApplyConfiguration represents an declarative configuration of the JWTToken type for use
// with apply.
type JWTTokenApplyConfiguration struct {
	IssuedAt  *int64  `json:"iat,omitempty"`
	ExpiresAt *int64  `json:"exp,omitempty"`
	ID        *string `json:"id,omitempty"`
}

// JWTTokenApplyConfiguration constructs an declarative configuration of the JWTToken type for use with
// apply.
func JWTToken() *JWTTokenApplyConfiguration {
	return &JWTTokenApplyConfiguration{}
}

// WithIssuedAt sets the IssuedAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the IssuedAt field is set to the value of the last call.
func (b *JWTTokenApplyConfiguration) WithIssuedAt(value int64) *JWTTokenApplyConfiguration {
	b.IssuedAt = &value
	return b
}

// WithExpiresAt sets the ExpiresAt field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExpiresAt field is set to the value of the last call.
func (b *JWTTokenApplyConfiguration) WithExpiresAt(value int64) *JWTTokenApplyConfiguration {
	b.ExpiresAt = &value
	return b
}

// WithID sets the ID field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ID field is set to the value of the last call.
func (b *JWTTokenApplyConfiguration) WithID(value string) *JWTTokenApplyConfiguration {
	b.ID = &value
	return b
}
