// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// OperationInitiatorApplyConfiguration represents an declarative configuration of the OperationInitiator type for use
// with apply.
type OperationInitiatorApplyConfiguration struct {
	Username  *string `json:"username,omitempty"`
	Automated *bool   `json:"automated,omitempty"`
}

// OperationInitiatorApplyConfiguration constructs an declarative configuration of the OperationInitiator type for use with
// apply.
func OperationInitiator() *OperationInitiatorApplyConfiguration {
	return &OperationInitiatorApplyConfiguration{}
}

// WithUsername sets the Username field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Username field is set to the value of the last call.
func (b *OperationInitiatorApplyConfiguration) WithUsername(value string) *OperationInitiatorApplyConfiguration {
	b.Username = &value
	return b
}

// WithAutomated sets the Automated field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Automated field is set to the value of the last call.
func (b *OperationInitiatorApplyConfiguration) WithAutomated(value bool) *OperationInitiatorApplyConfiguration {
	b.Automated = &value
	return b
}
