// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// PullRequestGeneratorAzureDevOpsApplyConfiguration represents an declarative configuration of the PullRequestGeneratorAzureDevOps type for use
// with apply.
type PullRequestGeneratorAzureDevOpsApplyConfiguration struct {
	Organization *string                      `json:"organization,omitempty"`
	Project      *string                      `json:"project,omitempty"`
	Repo         *string                      `json:"repo,omitempty"`
	API          *string                      `json:"api,omitempty"`
	TokenRef     *SecretRefApplyConfiguration `json:"tokenRef,omitempty"`
	Labels       []string                     `json:"labels,omitempty"`
}

// PullRequestGeneratorAzureDevOpsApplyConfiguration constructs an declarative configuration of the PullRequestGeneratorAzureDevOps type for use with
// apply.
func PullRequestGeneratorAzureDevOps() *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	return &PullRequestGeneratorAzureDevOpsApplyConfiguration{}
}

// WithOrganization sets the Organization field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Organization field is set to the value of the last call.
func (b *PullRequestGeneratorAzureDevOpsApplyConfiguration) WithOrganization(value string) *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	b.Organization = &value
	return b
}

// WithProject sets the Project field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Project field is set to the value of the last call.
func (b *PullRequestGeneratorAzureDevOpsApplyConfiguration) WithProject(value string) *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	b.Project = &value
	return b
}

// WithRepo sets the Repo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repo field is set to the value of the last call.
func (b *PullRequestGeneratorAzureDevOpsApplyConfiguration) WithRepo(value string) *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	b.Repo = &value
	return b
}

// WithAPI sets the API field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the API field is set to the value of the last call.
func (b *PullRequestGeneratorAzureDevOpsApplyConfiguration) WithAPI(value string) *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	b.API = &value
	return b
}

// WithTokenRef sets the TokenRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TokenRef field is set to the value of the last call.
func (b *PullRequestGeneratorAzureDevOpsApplyConfiguration) WithTokenRef(value *SecretRefApplyConfiguration) *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	b.TokenRef = value
	return b
}

// WithLabels adds the given value to the Labels field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Labels field.
func (b *PullRequestGeneratorAzureDevOpsApplyConfiguration) WithLabels(values ...string) *PullRequestGeneratorAzureDevOpsApplyConfiguration {
	for i := range values {
		b.Labels = append(b.Labels, values[i])
	}
	return b
}
