// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1alpha1

// PullRequestGeneratorBitbucketApplyConfiguration represents an declarative configuration of the PullRequestGeneratorBitbucket type for use
// with apply.
type PullRequestGeneratorBitbucketApplyConfiguration struct {
	Owner       *string                                      `json:"owner,omitempty"`
	Repo        *string                                      `json:"repo,omitempty"`
	API         *string                                      `json:"api,omitempty"`
	BasicAuth   *BasicAuthBitbucketServerApplyConfiguration  `json:"basicAuth,omitempty"`
	BearerToken *BearerTokenBitbucketCloudApplyConfiguration `json:"bearerToken,omitempty"`
}

// PullRequestGeneratorBitbucketApplyConfiguration constructs an declarative configuration of the PullRequestGeneratorBitbucket type for use with
// apply.
func PullRequestGeneratorBitbucket() *PullRequestGeneratorBitbucketApplyConfiguration {
	return &PullRequestGeneratorBitbucketApplyConfiguration{}
}

// WithOwner sets the Owner field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Owner field is set to the value of the last call.
func (b *PullRequestGeneratorBitbucketApplyConfiguration) WithOwner(value string) *PullRequestGeneratorBitbucketApplyConfiguration {
	b.Owner = &value
	return b
}

// WithRepo sets the Repo field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Repo field is set to the value of the last call.
func (b *PullRequestGeneratorBitbucketApplyConfiguration) WithRepo(value string) *PullRequestGeneratorBitbucketApplyConfiguration {
	b.Repo = &value
	return b
}

// WithAPI sets the API field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the API field is set to the value of the last call.
func (b *PullRequestGeneratorBitbucketApplyConfiguration) WithAPI(value string) *PullRequestGeneratorBitbucketApplyConfiguration {
	b.API = &value
	return b
}

// WithBasicAuth sets the BasicAuth field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BasicAuth field is set to the value of the last call.
func (b *PullRequestGeneratorBitbucketApplyConfiguration) WithBasicAuth(value *BasicAuthBitbucketServerApplyConfiguration) *PullRequestGeneratorBitbucketApplyConfiguration {
	b.BasicAuth = value
	return b
}

// WithBearerToken sets the BearerToken field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the BearerToken field is set to the value of the last call.
func (b *PullRequestGeneratorBitbucketApplyConfiguration) WithBearerToken(value *BearerTokenBitbucketCloudApplyConfiguration) *PullRequestGeneratorBitbucketApplyConfiguration {
	b.BearerToken = value
	return b
}
