// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/seal-io/walrus/pkg/apis/walruscore/v1"
	walruscorev1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walruscore/v1"
	scheme "github.com/seal-io/walrus/pkg/clients/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceDefinitionMatchingRulesGetter has a method to return a ResourceDefinitionMatchingRuleInterface.
// A group's client should implement this interface.
type ResourceDefinitionMatchingRulesGetter interface {
	ResourceDefinitionMatchingRules(namespace string) ResourceDefinitionMatchingRuleInterface
}

// ResourceDefinitionMatchingRuleInterface has methods to work with ResourceDefinitionMatchingRule resources.
type ResourceDefinitionMatchingRuleInterface interface {
	Create(ctx context.Context, resourceDefinitionMatchingRule *v1.ResourceDefinitionMatchingRule, opts metav1.CreateOptions) (*v1.ResourceDefinitionMatchingRule, error)
	Update(ctx context.Context, resourceDefinitionMatchingRule *v1.ResourceDefinitionMatchingRule, opts metav1.UpdateOptions) (*v1.ResourceDefinitionMatchingRule, error)
	UpdateStatus(ctx context.Context, resourceDefinitionMatchingRule *v1.ResourceDefinitionMatchingRule, opts metav1.UpdateOptions) (*v1.ResourceDefinitionMatchingRule, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ResourceDefinitionMatchingRule, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ResourceDefinitionMatchingRuleList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceDefinitionMatchingRule, err error)
	Apply(ctx context.Context, resourceDefinitionMatchingRule *walruscorev1.ResourceDefinitionMatchingRuleApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceDefinitionMatchingRule, err error)
	ApplyStatus(ctx context.Context, resourceDefinitionMatchingRule *walruscorev1.ResourceDefinitionMatchingRuleApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceDefinitionMatchingRule, err error)
	ResourceDefinitionMatchingRuleExpansion
}

// resourceDefinitionMatchingRules implements ResourceDefinitionMatchingRuleInterface
type resourceDefinitionMatchingRules struct {
	client rest.Interface
	ns     string
}

// newResourceDefinitionMatchingRules returns a ResourceDefinitionMatchingRules
func newResourceDefinitionMatchingRules(c *WalruscoreV1Client, namespace string) *resourceDefinitionMatchingRules {
	return &resourceDefinitionMatchingRules{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceDefinitionMatchingRule, and returns the corresponding resourceDefinitionMatchingRule object, and an error if there is any.
func (c *resourceDefinitionMatchingRules) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ResourceDefinitionMatchingRule, err error) {
	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceDefinitionMatchingRules that match those selectors.
func (c *resourceDefinitionMatchingRules) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ResourceDefinitionMatchingRuleList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ResourceDefinitionMatchingRuleList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceDefinitionMatchingRules.
func (c *resourceDefinitionMatchingRules) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a resourceDefinitionMatchingRule and creates it.  Returns the server's representation of the resourceDefinitionMatchingRule, and an error, if there is any.
func (c *resourceDefinitionMatchingRules) Create(ctx context.Context, resourceDefinitionMatchingRule *v1.ResourceDefinitionMatchingRule, opts metav1.CreateOptions) (result *v1.ResourceDefinitionMatchingRule, err error) {
	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceDefinitionMatchingRule).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a resourceDefinitionMatchingRule and updates it. Returns the server's representation of the resourceDefinitionMatchingRule, and an error, if there is any.
func (c *resourceDefinitionMatchingRules) Update(ctx context.Context, resourceDefinitionMatchingRule *v1.ResourceDefinitionMatchingRule, opts metav1.UpdateOptions) (result *v1.ResourceDefinitionMatchingRule, err error) {
	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(resourceDefinitionMatchingRule.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceDefinitionMatchingRule).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *resourceDefinitionMatchingRules) UpdateStatus(ctx context.Context, resourceDefinitionMatchingRule *v1.ResourceDefinitionMatchingRule, opts metav1.UpdateOptions) (result *v1.ResourceDefinitionMatchingRule, err error) {
	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(resourceDefinitionMatchingRule.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceDefinitionMatchingRule).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the resourceDefinitionMatchingRule and deletes it. Returns an error if one occurs.
func (c *resourceDefinitionMatchingRules) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceDefinitionMatchingRules) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched resourceDefinitionMatchingRule.
func (c *resourceDefinitionMatchingRules) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceDefinitionMatchingRule, err error) {
	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied resourceDefinitionMatchingRule.
func (c *resourceDefinitionMatchingRules) Apply(ctx context.Context, resourceDefinitionMatchingRule *walruscorev1.ResourceDefinitionMatchingRuleApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceDefinitionMatchingRule, err error) {
	if resourceDefinitionMatchingRule == nil {
		return nil, fmt.Errorf("resourceDefinitionMatchingRule provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(resourceDefinitionMatchingRule)
	if err != nil {
		return nil, err
	}
	name := resourceDefinitionMatchingRule.Name
	if name == nil {
		return nil, fmt.Errorf("resourceDefinitionMatchingRule.Name must be provided to Apply")
	}
	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *resourceDefinitionMatchingRules) ApplyStatus(ctx context.Context, resourceDefinitionMatchingRule *walruscorev1.ResourceDefinitionMatchingRuleApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceDefinitionMatchingRule, err error) {
	if resourceDefinitionMatchingRule == nil {
		return nil, fmt.Errorf("resourceDefinitionMatchingRule provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(resourceDefinitionMatchingRule)
	if err != nil {
		return nil, err
	}

	name := resourceDefinitionMatchingRule.Name
	if name == nil {
		return nil, fmt.Errorf("resourceDefinitionMatchingRule.Name must be provided to Apply")
	}

	result = &v1.ResourceDefinitionMatchingRule{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("resourcedefinitionmatchingrules").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
