// SPDX-FileCopyrightText: 2024 Seal, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by "walrus", DO NOT EDIT.

package v1

import (
	"context"
	json "encoding/json"
	"fmt"
	"time"

	v1 "github.com/seal-io/walrus/pkg/apis/walruscore/v1"
	walruscorev1 "github.com/seal-io/walrus/pkg/clients/applyconfiguration/walruscore/v1"
	scheme "github.com/seal-io/walrus/pkg/clients/clientset/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ResourceHooksGetter has a method to return a ResourceHookInterface.
// A group's client should implement this interface.
type ResourceHooksGetter interface {
	ResourceHooks(namespace string) ResourceHookInterface
}

// ResourceHookInterface has methods to work with ResourceHook resources.
type ResourceHookInterface interface {
	Create(ctx context.Context, resourceHook *v1.ResourceHook, opts metav1.CreateOptions) (*v1.ResourceHook, error)
	Update(ctx context.Context, resourceHook *v1.ResourceHook, opts metav1.UpdateOptions) (*v1.ResourceHook, error)
	UpdateStatus(ctx context.Context, resourceHook *v1.ResourceHook, opts metav1.UpdateOptions) (*v1.ResourceHook, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*v1.ResourceHook, error)
	List(ctx context.Context, opts metav1.ListOptions) (*v1.ResourceHookList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceHook, err error)
	Apply(ctx context.Context, resourceHook *walruscorev1.ResourceHookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceHook, err error)
	ApplyStatus(ctx context.Context, resourceHook *walruscorev1.ResourceHookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceHook, err error)
	ResourceHookExpansion
}

// resourceHooks implements ResourceHookInterface
type resourceHooks struct {
	client rest.Interface
	ns     string
}

// newResourceHooks returns a ResourceHooks
func newResourceHooks(c *WalruscoreV1Client, namespace string) *resourceHooks {
	return &resourceHooks{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the resourceHook, and returns the corresponding resourceHook object, and an error if there is any.
func (c *resourceHooks) Get(ctx context.Context, name string, options metav1.GetOptions) (result *v1.ResourceHook, err error) {
	result = &v1.ResourceHook{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ResourceHooks that match those selectors.
func (c *resourceHooks) List(ctx context.Context, opts metav1.ListOptions) (result *v1.ResourceHookList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1.ResourceHookList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("resourcehooks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested resourceHooks.
func (c *resourceHooks) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("resourcehooks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a resourceHook and creates it.  Returns the server's representation of the resourceHook, and an error, if there is any.
func (c *resourceHooks) Create(ctx context.Context, resourceHook *v1.ResourceHook, opts metav1.CreateOptions) (result *v1.ResourceHook, err error) {
	result = &v1.ResourceHook{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("resourcehooks").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceHook).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a resourceHook and updates it. Returns the server's representation of the resourceHook, and an error, if there is any.
func (c *resourceHooks) Update(ctx context.Context, resourceHook *v1.ResourceHook, opts metav1.UpdateOptions) (result *v1.ResourceHook, err error) {
	result = &v1.ResourceHook{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(resourceHook.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceHook).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *resourceHooks) UpdateStatus(ctx context.Context, resourceHook *v1.ResourceHook, opts metav1.UpdateOptions) (result *v1.ResourceHook, err error) {
	result = &v1.ResourceHook{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(resourceHook.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(resourceHook).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the resourceHook and deletes it. Returns an error if one occurs.
func (c *resourceHooks) Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *resourceHooks) DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("resourcehooks").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched resourceHook.
func (c *resourceHooks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *v1.ResourceHook, err error) {
	result = &v1.ResourceHook{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// Apply takes the given apply declarative configuration, applies it and returns the applied resourceHook.
func (c *resourceHooks) Apply(ctx context.Context, resourceHook *walruscorev1.ResourceHookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceHook, err error) {
	if resourceHook == nil {
		return nil, fmt.Errorf("resourceHook provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(resourceHook)
	if err != nil {
		return nil, err
	}
	name := resourceHook.Name
	if name == nil {
		return nil, fmt.Errorf("resourceHook.Name must be provided to Apply")
	}
	result = &v1.ResourceHook{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(*name).
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *resourceHooks) ApplyStatus(ctx context.Context, resourceHook *walruscorev1.ResourceHookApplyConfiguration, opts metav1.ApplyOptions) (result *v1.ResourceHook, err error) {
	if resourceHook == nil {
		return nil, fmt.Errorf("resourceHook provided to Apply must not be nil")
	}
	patchOpts := opts.ToPatchOptions()
	data, err := json.Marshal(resourceHook)
	if err != nil {
		return nil, err
	}

	name := resourceHook.Name
	if name == nil {
		return nil, fmt.Errorf("resourceHook.Name must be provided to Apply")
	}

	result = &v1.ResourceHook{}
	err = c.client.Patch(types.ApplyPatchType).
		Namespace(c.ns).
		Resource("resourcehooks").
		Name(*name).
		SubResource("status").
		VersionedParams(&patchOpts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
